apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  labels:
    app.kubernetes.io/part-of: book-lens
type: Opaque
stringData:
  DJANGO_SECRET_KEY: change-me
  DB_PASSWORD: change-me
  POSTGRES_PASSWORD: change-me
