# Generated by Codex on 2026-06-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
        ("characters", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="Persona",
                    fields=[
                        (
                            "id",
                            models.BigAutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("greeting_open", models.TextField(blank=True, null=True)),
                        ("greeting_close", models.TextField(blank=True, null=True)),
                        ("personality", models.TextField(blank=True, null=True)),
                        ("speech_style", models.TextField(blank=True, null=True)),
                        ("catchphrase", models.TextField(blank=True, null=True)),
                        ("bio", models.TextField(blank=True, null=True)),
                        ("tags", models.JSONField(blank=True, default=list)),
                        ("opening_scene", models.TextField(blank=True, null=True)),
                        ("era", models.CharField(blank=True, max_length=100, null=True)),
                        ("background", models.TextField(blank=True, null=True)),
                        (
                            "user_role",
                            models.CharField(blank=True, max_length=100, null=True),
                        ),
                        (
                            "user_relationship",
                            models.CharField(blank=True, max_length=100, null=True),
                        ),
                        ("system_prompt", models.TextField(blank=True, null=True)),
                        (
                            "approved_status",
                            models.CharField(blank=True, max_length=50, null=True),
                        ),
                        ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                        ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                        (
                            "book",
                            models.ForeignKey(
                                db_column="book_id",
                                on_delete=django.db.models.deletion.DO_NOTHING,
                                related_name="personas",
                                to="books.book",
                            ),
                        ),
                        (
                            "character",
                            models.ForeignKey(
                                db_column="character_id",
                                on_delete=django.db.models.deletion.DO_NOTHING,
                                related_name="personas",
                                to="characters.character",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "persona",
                        "managed": False,
                        "ordering": ["id"],
                    },
                ),
            ],
        ),
    ]
