# Generated by Codex on 2026-06-16

import django.db.models.deletion
from django.db import migrations, models


def create_persona_table_if_missing(apps, schema_editor):
    Persona = apps.get_model("characters", "Persona")
    table_name = Persona._meta.db_table
    existing_tables = schema_editor.connection.introspection.table_names()
    if table_name in existing_tables:
        return
    schema_editor.create_model(Persona)


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0002_persona"),
    ]

    operations = [
        migrations.RunPython(
            create_persona_table_if_missing,
            migrations.RunPython.noop,
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name="persona",
                    name="book",
                    field=models.ForeignKey(
                        db_column="book_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personas",
                        to="books.book",
                    ),
                ),
                migrations.AlterField(
                    model_name="persona",
                    name="character",
                    field=models.ForeignKey(
                        db_column="character_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personas",
                        to="characters.character",
                    ),
                ),
            ],
        ),
    ]
