# Generated by Django 6.0.6 on 2026-06-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(unique=True)),
                (
                    "difficulty_level",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "response_length",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("age_group", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "explanation_style",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("interests", models.JSONField(blank=True, default=list)),
                ("instruction", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "user_preference",
                "managed": False,
            },
        ),
    ]
