resources:
  - frontend.yaml
  - django.yaml
  - nginx.yaml

configMapGenerator:
  - name: nginx-config
    files:
      - default.conf=../../nginx/default.conf

generatorOptions:
  disableNameSuffixHash: true
