# Generated by Codex on 2026-06-16

import django.db.models.deletion
import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        pgvector.django.VectorExtension(),
        migrations.CreateModel(
            name="BookContentChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chunk_index", models.PositiveIntegerField()),
                ("content", models.TextField()),
                (
                    "embedding",
                    pgvector.django.VectorField(
                        blank=True,
                        dimensions=1024,
                        null=True,
                    ),
                ),
                ("embed_status", models.CharField(blank=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "book_content",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="books.bookcontent",
                    ),
                ),
            ],
            options={
                "db_table": "book_content_chunk",
                "ordering": ["book_content_id", "chunk_index"],
                "indexes": [
                    pgvector.django.HnswIndex(
                        ef_construction=64,
                        fields=["embedding"],
                        m=16,
                        name="bcc_embedding_hnsw",
                        opclasses=["vector_cosine_ops"],
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("book_content", "chunk_index"),
                        name="unique_book_content_chunk_index",
                    ),
                ],
            },
        ),
    ]
